// react-app/src/components/CardContent.js
import React from 'react';

const CardContent = ({ name, description }) => (
  <div className="card-content">
    <div className="content">
      <div className="name">{name}</div>
      <div className="description">{description}</div>
    </div>
  </div>
);

export default CardContent;

// angular-app/src/app/shared/card-content.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-card-content',
  template: `
    <div class="card-content">
      <div class="content">
        <div class="name">{{ name }}</div>
        <div class="description">{{ description }}</div>
      </div>
    </div>
  `
})
export class CardContentComponent implements OnInit {
  @Input() name;
  @Input() description;

  ngOnInit() {}
}
